### ISSUE TITLE
Default connection is shared between producer and consumer

### ISSUE THREAD

**Issue by tanmauec** [santanusinha/dropwizard-rabbitmq-actors#72]
In a recent outage in our backend service using rmq actor bundle to connect to rmq, we observed that publishers were not able to publish to RMQ and consumers were not consuming from RMQ as well,

all while buildup of 2.1 million messages in the queue.

On inspecting the rmq bundle code, we found that single connection is shared between producer and consumer, indicating if RMQ was in flow state, it would have blocked consumers as well, which is a non-desirable outcome of flow control.

As a result, the whole system got stuck.

While, we also may need to enhance the healthcheck() function to check if rmq is in flow state, to begin with, proposing for separating the default connection for producer and consumer

This is also called out as one of common mistakes developers may make with RMQ

https://www.rabbitmq.com/connections.html#flow-control
https://www.cloudamqp.com/blog/part4-rabbitmq-13-common-errors.html

PR: https://github.com/santanusinha/dropwizard-rabbitmq-actors/pull/71

**Comment by santanusinha** [comment]
Message build up due to slow consumption would anyways lead to memory high
watermark and flow control. What is the point of creating more connections?

**Comment by tanmauec** [comment]
Agreed that we should be frugal in the number of bootstrapped connections.

I believe, flow control is a dynamic mechanism to prevent a queue under stress from reaching High watermark by blocking publishers while consumers continue their job, the RMQ will try flow control as much as possible to prevent HWM scenario.

Allowing flow control to work effectively may become the difference between RMQ cluster reaching HWM and recovering from a stressed state to normal.

I submit that maintaining the hygiene of keeping separate default connection for producer and consumer will prevent users of the rmq bundle from stepping into this pithole if they have failed to define custom producer and consumer configs which maybe more common than we can currently quantify!

**Comment by tanmauec** [comment]
@santanusinha Thanks for merging PR. Closing issue
https://github.com/santanusinha/dropwizard-rabbitmq-actors/pull/71
